apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-autoscaler
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-autoscaler
  template:
    metadata:
      labels:
        app: ai-autoscaler
    spec:
      serviceAccountName: autoscaler-sa  # ✅ this is required for RBAC to work
      containers:
      - name: ai-autoscaler
        image: your-dockerhub/ai-autoscaler:latest
        imagePullPolicy: Always  # optional but recommended
