apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-autoscaler-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: custom-autoscaler-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-autoscaler-rolebinding
subjects:
- kind: ServiceAccount
  name: custom-autoscaler-sa
roleRef:
  kind: Role
  name: custom-autoscaler-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-autoscaler-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-autoscaler-controller
  template:
    metadata:
      labels:
        app: custom-autoscaler-controller
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: custom-autoscaler-sa
      containers:
      - name: controller
        image: marwanhabib/custom-autoscaler-controller:v1
        env:
        - name: SUGGESTION_SERVICE_URL
          value: "http://suggestion-service:5000/suggestion"
        - name: POLL_INTERVAL_SECONDS
          value: "60"