# suggestion-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: suggestion-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suggestion-server
  template:
    metadata:
      labels:
        app: suggestion-server
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: custom-autoscaler-sa
      containers:
      - name: suggestion
        image: marwanhabib/custom-autoscaler-suggestion-flask:dummy
        ports:
        - containerPort: 5000
        env:
        - name: PROMETHEUS_URL
          value: "http://prometheus-nodeport.monitoring.svc.cluster.local:9090"
        - name: MODEL_SERVICE_URL
          value: "http://model-service:8000/predict"
---
apiVersion: v1
kind: Service
metadata:
  name: suggestion-service
spec:
  selector:
    app: suggestion-server
  ports:
  # The service listens on port 5000 and forwards to the container's port 5000
  - protocol: TCP
    port: 5000
    targetPort: 5000